// Imports all fontawesome core and solid icons

import {library} from '@fortawesome/fontawesome-svg-core';
import {
  faUser,
  faSort,
  faSortUp,
  faSortDown,
  faSync,
  faEye,
  faBan,
  faTimes,
  faArrowLeft,
  faSave,
  faPlus,
  faPencilAlt,
  faBars,
  faThList,
  faUserPlus,
  faRoad,
  faTachometerAlt,
  faHeart,
  faList,
  faBell,
  faBook,
  faHdd,
  faFlag,
  faWrench,
  faClock,
  faCloud,
  faSignOutAlt,
  faSignInAlt,
  faCalendarAlt,
  faSearch,
  faTrashAlt,
  faAsterisk,
  faTasks,
  faHome,
  faComments,
  faPaperPlane,
  faGrinAlt,
  faEllipsisH,
  faThumbsDown,
  faThumbsUp,
  faCircle,
  faPaperclip,
  faAngry,
  faSadTear,
  faListAlt,
  faCheck,
  faSyncAlt,
  faQuestionCircle,
} from '@fortawesome/free-solid-svg-icons';

// Adds the SVG icon to the library so you can use it in your page
library.add(faUser);
library.add(faSort);
library.add(faSortUp);
library.add(faSortDown);
library.add(faSync);
library.add(faEye);
library.add(faBan);
library.add(faTimes);
library.add(faArrowLeft);
library.add(faSave);
library.add(faPlus);
library.add(faPencilAlt);
library.add(faBars);
library.add(faHome);
library.add(faThList);
library.add(faUserPlus);
library.add(faRoad);
library.add(faTachometerAlt);
library.add(faHeart);
library.add(faList);
library.add(faBell);
library.add(faTasks);
library.add(faBook);
library.add(faHdd);
library.add(faFlag);
library.add(faWrench);
library.add(faClock);
library.add(faCloud);
library.add(faSignOutAlt);
library.add(faSignInAlt);
library.add(faCalendarAlt);
library.add(faSearch);
library.add(faTrashAlt);
library.add(faAsterisk);
library.add(faComments);
library.add(faPaperPlane);
library.add(faGrinAlt);
library.add(faEllipsisH);
library.add(faThumbsUp);
library.add(faThumbsDown);
library.add(faCircle);
library.add(faPaperclip);
library.add(faAngry);
library.add(faSadTear);
library.add(faListAlt);
library.add(faCheck);
library.add(faSyncAlt);
library.add(faQuestionCircle);
